default: &default
  adapter: postgresql  # This tells Rails to use the 'pg' gem
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432 

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

